import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const LoginPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SharedSongs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>Login</main>

      <footer className={styles.footer}>foot</footer>
    </div>
  );
};

export default LoginPage;
